const NO_ERROR = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  NO_ERROR,
  CREATED,
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
};
// const ERROR__DEFAULT = 500;
// const ERROR__REPEATS_EMAIL = 409;
// const ERROR__NO_ACCESS = 403;
